### ISSUE TITLE
Widget with profile picture and alternate design

### ISSUE THREAD

**Issue by realFPS** [pizidavi/Trakt-Widgets-2#8]
Something like, will it be possible?|

![image](https://github.com/pizidavi/Trakt-Widgets-2/assets/77321589/ee8e6cbd-2276-4f8a-a3b4-07771292a6a4)

**Comment by pizidavi** [comment]
Done! Use `fanart-overlay` in `View` for it 💪

**Comment by realFPS** [comment]
Thank you ❤️
